#### Getting started. - easiest way is to download miniconda (or conda)
    https://conda.io/docs/user-guide/install/index.html
        
    Best to keep in line with Shareinsights version, so conda 5.1.1 and python 2.7  
    If you have installed vagrant box, everything you need is there.  
    
    Why use python ?
    1. ShareInsights does not support all operations.  
    2. Very specific operations need. 
    3. Even before loading data in share-insights. (alternative to excel)
    4. Misc - Scraping webpages for data, Getting data from apis etc.
    
quickly cover basic syntax - https://learnxinyminutes.com/docs/python/ (20 mins)  



In [37]:
aList = [1,2,3,4,5]
aList

[1, 2, 3, 4, 5]

In [38]:
aList.append(6)
aList

[1, 2, 3, 4, 5, 6]

In [5]:
anotherList = range(1,6)
list(anotherList)

[1, 2, 3, 4, 5]

In [12]:
aMatrix = [aList] *3
aMatrix

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

In [13]:
aMatrix[:,1]

TypeError: list indices must be integers or slices, not tuple

it is a list of list and not a matrix (ndArray). Cumbersome to use. numpy to the rescue

In [20]:
import numpy as np

In [39]:
aMatrix = np.array(aMatrix)
aMatrix

array([[1, 2, 3, 4, 5, 6, 6],
       [1, 2, 3, 4, 5, 6, 6],
       [1, 2, 3, 4, 5, 6, 6]])

In [42]:
aMatrix[1,:]

array([1, 2, 3, 4, 5, 6, 6])

In [43]:
aMatrix[:,1]

array([2, 2, 2])

In [50]:
aMatrix.shape

(3, 7)

In [81]:
np.c_[aMatrix,np.zeros(aMatrix.shape[0])]

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  6.,  0.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  6.,  0.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  6.,  0.]])

In [51]:
aMatrix.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6],
       [6, 6, 6]])

In [61]:
aVector = np.array(range(0,7)).reshape(7,1)
aVector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [82]:
np.c_[aMatrix.T,aVector]

array([[1, 1, 1, 0],
       [2, 2, 2, 1],
       [3, 3, 3, 2],
       [4, 4, 4, 3],
       [5, 5, 5, 4],
       [6, 6, 6, 5],
       [6, 6, 6, 6]])

In [60]:
help(np.concatenate)

Help on built-in function concatenate in module numpy.core.multiarray:

concatenate(...)
    concatenate((a1, a2, ...), axis=0)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  Default is 0.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
                  near-equal size.
    split : Split array into a list of multiple sub-arrays of equal size.
    hsplit : Split array into multiple sub-arrays horizontally (column wise)
    vsplit : Split array into multiple sub-arrays vertically (row wise)
    dsp

Numpy has many ther operations like, min , max , cumsum , stack , append , concatenate etc.
Find some here-  https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

In [ ]:

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
a=1
b=2

In [13]:
a
b

1

2

In [25]:
%%time
import time
sum = 0
for x in range(10000):
    sum = sum+x# sleep for 0.01 seconds

CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 2.85 ms


In [29]:
#you can execute shell commands too
!ls
print('------------')
!pip list | grep pa

flow1_remove_columns_1504786008180.limit10000.csv  shareinsight-dark.png
Python_for_Solutions_Team			   transactions.limit10000.csv
python_for_solutions_team.ipynb
------------
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
ipyparallel (6.0.2)
jmespath (0.9.3)
msgpack-numpy (0.4.1)
msgpack-python (0.4.8)
multipledispatch (0.4.9)
packaging (16.8)
pandas (0.20.1)
pandas-datareader (0.6.0)
pandocfilters (1.4.1)
partd (0.3.8)
pathlib2 (2.2.1)
patsy (0.4.1)
pycparser (2.17)
pyparsing (2.1.4)
singledispatch (3.4.0.3)
spacy (2.0.10)
testpath (0.3)
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


### MARKDOWN CELLS
1. Support Lists
2. **Support bold**, *italics* etc.
3. [Support inline hyperinks like this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet "Markdown Tips")



Images too: 
![alt text](./shareinsight-dark.png "Shareinsights Logo")

### PANDAS

Most important library for Our team currently.  
Dataframe is the most importnt data structure to understand

In [14]:
import pandas as pd

In [15]:
# create a dataframe from a numpy array
df = pd.DataFrame(aMatrix.T,columns=['age','height','weight'])
df

NameError: name 'aMatrix' is not defined

In [96]:
df['names'] = list('abcdefg')

In [97]:
df

age  height  weight names
0    1       1       1     a
1    2       2       2     b
2    3       3       3     c
3    4       4       4     d
4    5       5       5     e
5    6       6       6     f
6    6       6       6     g

In [ ]:
df = pd.read_csv()

indexing, conditional indexing , 

In [31]:
df = pd.read_csv('./user_expense.csv')
df.head()

username  year_nm  month_nm   mcc_category date_time expense_date  \
0     Ruth Abady     2017         1        utility    Jan-17   2017-01-01   
1  Michael Abady     2017         1  entertainment    Jan-17   2017-01-01   
2  Erika Abahazy     2017         1  entertainment    Jan-17   2017-01-01   
3  Marlinda Abad     2017         1  entertainment    Jan-17   2017-01-01   
4   Meriem Abada     2017         1        grocery    Jan-17   2017-01-01   

   sum_expense  
0        124.0  
1        556.0  
2        860.0  
3        890.0  
4        672.0

In [32]:
df.describe()

year_nm  month_nm  sum_expense
count   1000.0    1000.0  1000.000000
mean    2017.0       1.0   458.055000
std        0.0       0.0   359.107486
min     2017.0       1.0    96.000000
25%     2017.0       1.0   128.000000
50%     2017.0       1.0   392.500000
75%     2017.0       1.0   654.500000
max     2017.0       1.0  2386.000000

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
username        1000 non-null object
year_nm         1000 non-null int64
month_nm        1000 non-null int64
mcc_category    1000 non-null object
date_time       1000 non-null object
expense_date    1000 non-null object
sum_expense     1000 non-null float64
dtypes: float64(1), int64(2), object(4)
memory usage: 54.8+ KB


A dataframe is composed of series. Both columns and Rows are pd.Series datatype.  
 A series is a list of values with a associated index.  
 Columns - column values with the dataframe index  
 Rows - Row Values with index as column names.  
 Means we can use series functions on them  
 
 
 https://pandas.pydata.org/pandas-docs/stable/dsintro.html

In [34]:
df['mcc_category']

0            utility
1      entertainment
2      entertainment
3      entertainment
4            grocery
5            savings
6            grocery
7            savings
8            utility
9            utility
10           grocery
11           utility
12           savings
13           savings
14           savings
15           utility
16           savings
17           grocery
18     entertainment
19           savings
20     entertainment
21           utility
22           grocery
23           savings
24           grocery
25           utility
26           grocery
27           grocery
28     entertainment
29     entertainment
           ...      
970          utility
971          grocery
972          savings
973    entertainment
974          grocery
975          utility
976    entertainment
977    entertainment
978          savings
979          grocery
980          utility
981    entertainment
982    entertainment
983          utility
984          savings
985          grocery
986    entert

In [11]:
df.iloc[0]

username        Sisa Abadilla
year_nm                  2015
month_nm                    5
mcc_category    entertainment
date_time              May-15
expense_date       2015-05-01
sum_expense              1210
Name: 0, dtype: object

In [13]:
type(df['mcc_category']),type(df.iloc[0])

(pandas.core.series.Series, pandas.core.series.Series)

In [ ]:
Common series functions - count() , value_counts , astype , values , iloc , loc , isna , isnull



https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html

In [14]:
df['mcc_category'].count() , 

(1000, grocery          266
 savings          245
 entertainment    245
 utility          244
 Name: mcc_category, dtype: int64)

In [15]:
df['mcc_category'].value_counts()

grocery          266
savings          245
entertainment    245
utility          244
Name: mcc_category, dtype: int64

In [ ]:
df['mcc_category'].aggregate()

In [ ]:
df['mcc_category'].apply()

#### stacking

In [45]:
pd.DataFrame(df.stack())

0
0   username          Ruth Abady
    year_nm                 2017
    month_nm                   1
    mcc_category         utility
    date_time             Jan-17
    expense_date      2017-01-01
    sum_expense              124
1   username       Michael Abady
    year_nm                 2017
    month_nm                   1
    mcc_category   entertainment
    date_time             Jan-17
    expense_date      2017-01-01
    sum_expense              556
2   username       Erika Abahazy
    year_nm                 2017
    month_nm                   1
    mcc_category   entertainment
    date_time             Jan-17
    expense_date      2017-01-01
    sum_expense              860
3   username       Marlinda Abad
    year_nm                 2017
    month_nm                   1
    mcc_category   entertainment
    date_time             Jan-17
    expense_date      2017-01-01
    sum_expense              890
4   username        Meriem Abada
    year_nm                 2017
...                          ...
995 expense_date      2017-01-01
    sum_expense             1597
996 username        Nader Abadir
    year_nm                 2017
    month_nm                   1
    mcc_category         savings
    date_time             Jan-17
    expense_date      2017-01-01
    sum_expense              103
997 username      Carolyn Ahrens
    year_nm                 2017
    month_nm                   1
    mcc_category         utility
    date_time             Jan-17
    expense_date      2017-01-01
    sum_expense              100
998 username      Felicia Ababio
    year_nm                 2017
    month_nm                   1
    mcc_category         grocery
    date_time             Jan-17
    expense_date      2017-01-01
    sum_expense              638
999 username       Nicole Ahrens
    year_nm                 2017
    month_nm                   1
    mcc_category         savings
    date_time             Jan-17
    expense_date      2017-01-01
    sum_expense              916

[7000 rows x 1 columns]

Difference between loc , iloc , ix etc.

#### Integer Indexing

In [35]:
df.iloc[-10:-3]

username  year_nm  month_nm   mcc_category date_time  \
990        Marlinda Abad     2017         1        grocery    Jan-17   
991           Dina Abadi     2017         1  entertainment    Jan-17   
992          Gale Ahrens     2017         1  entertainment    Jan-17   
993  Maria Abad-ceballos     2017         1        savings    Jan-17   
994          Albert Abad     2017         1  entertainment    Jan-17   
995         James Ahrens     2017         1        savings    Jan-17   
996         Nader Abadir     2017         1        savings    Jan-17   

    expense_date  sum_expense  
990   2017-01-01        206.0  
991   2017-01-01        335.0  
992   2017-01-01        740.0  
993   2017-01-01       1021.0  
994   2017-01-01        710.0  
995   2017-01-01       1597.0  
996   2017-01-01        103.0

#### Logical Indexing

In [36]:
df.loc[(df['username'] == 'Marlinda Abad') & (df['sum_expense'] > 300)]

username  year_nm  month_nm   mcc_category date_time expense_date  \
3  Marlinda Abad     2017         1  entertainment    Jan-17   2017-01-01   

   sum_expense  
3        890.0

#### MultiIndexing

In [39]:
dfIndexed = df.set_index(['username','mcc_category'])
dfIndexed.sort_index(inplace=True)

In [40]:
dfIndexed.head()

year_nm  month_nm date_time expense_date  \
username        mcc_category                                              
Abaco Fence     entertainment     2017         1    Jan-17   2017-01-01   
                grocery           2017         1    Jan-17   2017-01-01   
                utility           2017         1    Jan-17   2017-01-01   
Abacus Electric grocery           2017         1    Jan-17   2017-01-01   
                savings           2017         1    Jan-17   2017-01-01   

                               sum_expense  
username        mcc_category                
Abaco Fence     entertainment        728.0  
                grocery              658.0  
                utility              100.0  
Abacus Electric grocery              330.0  
                savings              135.0

In [42]:
dfIndexed.loc['Abaco Fence','entertainment']

year_nm               2017
month_nm                 1
date_time           Jan-17
expense_date    2017-01-01
sum_expense            728
Name: (Abaco Fence, entertainment), dtype: object

In [46]:
pd.DataFrame(dfIndexed.stack())

0
username        mcc_category                          
Abaco Fence     entertainment year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          728
                grocery       year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          658
                utility       year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          100
Abacus Electric grocery       year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          330
                savings       year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          135
Abdelhami Abada entertainment year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense         1934
...                                                ...
Yohanna Abadeer utility       year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          100
Youssef Abadir  grocery       year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          232
                savings       year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          780
                utility       year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          122
Zoila Abad      grocery       year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          313
                savings       year_nm             2017
                              month_nm               1
                              date_time         Jan-17
                              expense_date  2017-01-01
                              sum_expense          332

[5000 rows x 1 columns]

In [47]:
pd.DataFrame(dfIndexed.stack()).reset_index()

username   mcc_category       level_2           0
0         Abaco Fence  entertainment       year_nm        2017
1         Abaco Fence  entertainment      month_nm           1
2         Abaco Fence  entertainment     date_time      Jan-17
3         Abaco Fence  entertainment  expense_date  2017-01-01
4         Abaco Fence  entertainment   sum_expense         728
5         Abaco Fence        grocery       year_nm        2017
6         Abaco Fence        grocery      month_nm           1
7         Abaco Fence        grocery     date_time      Jan-17
8         Abaco Fence        grocery  expense_date  2017-01-01
9         Abaco Fence        grocery   sum_expense         658
10        Abaco Fence        utility       year_nm        2017
11        Abaco Fence        utility      month_nm           1
12        Abaco Fence        utility     date_time      Jan-17
13        Abaco Fence        utility  expense_date  2017-01-01
14        Abaco Fence        utility   sum_expense         100
15    Abacus Electric        grocery       year_nm        2017
16    Abacus Electric        grocery      month_nm           1
17    Abacus Electric        grocery     date_time      Jan-17
18    Abacus Electric        grocery  expense_date  2017-01-01
19    Abacus Electric        grocery   sum_expense         330
20    Abacus Electric        savings       year_nm        2017
21    Abacus Electric        savings      month_nm           1
22    Abacus Electric        savings     date_time      Jan-17
23    Abacus Electric        savings  expense_date  2017-01-01
24    Abacus Electric        savings   sum_expense         135
25    Abdelhami Abada  entertainment       year_nm        2017
26    Abdelhami Abada  entertainment      month_nm           1
27    Abdelhami Abada  entertainment     date_time      Jan-17
28    Abdelhami Abada  entertainment  expense_date  2017-01-01
29    Abdelhami Abada  entertainment   sum_expense        1934
...               ...            ...           ...         ...
4970  Yohanna Abadeer        utility       year_nm        2017
4971  Yohanna Abadeer        utility      month_nm           1
4972  Yohanna Abadeer        utility     date_time      Jan-17
4973  Yohanna Abadeer        utility  expense_date  2017-01-01
4974  Yohanna Abadeer        utility   sum_expense         100
4975   Youssef Abadir        grocery       year_nm        2017
4976   Youssef Abadir        grocery      month_nm           1
4977   Youssef Abadir        grocery     date_time      Jan-17
4978   Youssef Abadir        grocery  expense_date  2017-01-01
4979   Youssef Abadir        grocery   sum_expense         232
4980   Youssef Abadir        savings       year_nm        2017
4981   Youssef Abadir        savings      month_nm           1
4982   Youssef Abadir        savings     date_time      Jan-17
4983   Youssef Abadir        savings  expense_date  2017-01-01
4984   Youssef Abadir        savings   sum_expense         780
4985   Youssef Abadir        utility       year_nm        2017
4986   Youssef Abadir        utility      month_nm           1
4987   Youssef Abadir        utility     date_time      Jan-17
4988   Youssef Abadir        utility  expense_date  2017-01-01
4989   Youssef Abadir        utility   sum_expense         122
4990       Zoila Abad        grocery       year_nm        2017
4991       Zoila Abad        grocery      month_nm           1
4992       Zoila Abad        grocery     date_time      Jan-17
4993       Zoila Abad        grocery  expense_date  2017-01-01
4994       Zoila Abad        grocery   sum_expense         313
4995       Zoila Abad        savings       year_nm        2017
4996       Zoila Abad        savings      month_nm           1
4997       Zoila Abad        savings     date_time      Jan-17
4998       Zoila Abad        savings  expense_date  2017-01-01
4999       Zoila Abad        savings   sum_expense         332

[5000 rows x 4 columns]

#### Basic Plotting

##### Dealng with missing values

In [18]:
misDF = pd.read_csv('./patientsData.csv',na_values='?')
misDF.head()

ane     wbcc  htn  pot   al  hemo    sod   pcv    bgr      pc ...    bp  \
0    *      NaN  yes  5.5  NaN   8.5  142.0   NaN  207.0     NaN ...  90.0   
1  yes      NaN  yes  6.3  4.0   8.8  145.0  31.0  172.0  normal ...  90.0   
2   no      NaN  yes  NaN  NaN  12.6    NaN  43.0  100.0     NaN ...  70.0   
3   no      NaN  yes  4.0  1.0  13.8  135.0  41.0  109.0  normal ...  70.0   
4    *  10400.0  yes  NaN  0.0  12.0    NaN  41.0  230.0  normal ...  70.0   

  rbcc class     rbc   age   su         mrn    sc    sg cad  
0  NaN   ckd     NaN   NaN  NaN  6177857961   6.8   NaN  no  
1  NaN   ckd  normal  65.0  2.0  2948708273  13.5  1.01  no  
2  NaN   ckd     NaN  61.0  NaN  1830565307   2.1   NaN  no  
3  NaN   ckd     NaN  60.0  0.0  2449786134   3.9  1.01  no  
4  4.6   ckd     NaN  50.0  0.0  7480540882   2.2  1.01  no  

[5 rows x 26 columns]

In [24]:
misDF = misDF.replace('*',np.NaN)
misDF.shape

(400, 26)

In [28]:
misDF.dropna().shape

(157, 26)

In [27]:
misDF.dropna(axis=1).head()

class         mrn
0   ckd  6177857961
1   ckd  2948708273
2   ckd  1830565307
3   ckd  2449786134
4   ckd  7480540882

In [29]:
misDF.fillna(0)

ane     wbcc  htn  pot   al  hemo    sod   pcv    bgr        pc ...   \
0      0      0.0  yes  5.5  0.0   8.5  142.0   0.0  207.0         0 ...    
1    yes      0.0  yes  6.3  4.0   8.8  145.0  31.0  172.0    normal ...    
2     no      0.0  yes  0.0  0.0  12.6    0.0  43.0  100.0         0 ...    
3     no      0.0  yes  4.0  1.0  13.8  135.0  41.0  109.0    normal ...    
4      0  10400.0  yes  0.0  0.0  12.0    0.0  41.0  230.0    normal ...    
5    yes   6900.0  yes  0.0  0.0  12.3    0.0  41.0  341.0         0 ...    
6     no   6900.0   no  0.0  0.0  11.5    0.0   0.0    0.0    normal ...    
7    yes   9800.0  yes  5.7  4.0   7.3  135.0  20.0  255.0    normal ...    
8     no      0.0   no  0.0  0.0   0.0    0.0   0.0  103.0    normal ...    
9      0   8800.0  yes  5.6  3.0  10.9  132.0  31.0  253.0    normal ...    
10    no   7400.0  yes  4.9  3.0  10.9  137.0  34.0  214.0  abnormal ...    
11    no   4900.0   no  0.0  0.0  13.7    0.0  43.0  171.0  abnormal ...    
12    no      0.0   no  0.0  3.0   0.0    0.0   0.0    0.0  abnormal ...    
13    no      0.0   no  0.0  0.0  12.8    0.0  38.0  107.0    normal ...    
14    no  10500.0   no  4.4  1.0  12.2  141.0  36.0   78.0    normal ...    
15    no   7000.0   no  0.0  0.0  11.8    0.0  34.0   92.0    normal ...    
16    no   8000.0  yes  0.0  0.0   9.8    0.0  28.0  238.0    normal ...    
17    no   8800.0   no  0.0  0.0  11.9    0.0  36.0  103.0    normal ...    
18    no      0.0  yes  5.3  1.0   0.0  138.0   0.0  248.0         0 ...    
19    no      0.0  yes  0.0  0.0   0.0    0.0   0.0  108.0         0 ...    
20    no   9200.0  yes  4.1  0.0  13.0  136.0  38.0  303.0    normal ...    
21    no      0.0   no  3.8  0.0   0.0  138.0   0.0  117.0    normal ...    
22    no  12000.0  yes  3.8  3.0  11.5  131.0  35.0  490.0    normal ...    
23    no   7500.0  yes  4.6  4.0   7.9  140.0  26.0  163.0  abnormal ...    
24    no   7200.0  yes  0.0  0.0  11.3    0.0  36.0  120.0    normal ...    
25    no      0.0  yes  0.0  0.0   0.0    0.0   0.0  124.0         0 ...    
26    no  15700.0   no  2.9  3.0   9.6  114.0  31.0  241.0  abnormal ...    
27    no   9500.0  yes  4.3  2.0   0.0  130.0   0.0  192.0  abnormal ...    
28    no      0.0  yes  3.7  0.0  11.5  138.0  35.0  269.0         0 ...    
29    no      0.0   no  0.0  1.0   0.0    0.0   0.0    0.0  abnormal ...    
..   ...      ...  ...  ...  ...   ...    ...   ...    ...       ... ...    
370   no  11200.0   no  2.8  1.0  13.1  145.0  41.0   22.0    normal ...    
371   no   8600.0   no  4.7  0.0  11.0  141.0  35.0  111.0         0 ...    
372   no   4200.0  yes  3.0  0.0   0.0  113.0   0.0  261.0    normal ...    
373  yes  12400.0   no  3.5  4.0   8.3  125.0  23.0  107.0  abnormal ...    
374   no      0.0   no  0.0  2.0  13.2    0.0  41.0  215.0    normal ...    
375  yes   9800.0   no  4.3  2.0   9.8  139.0  34.0   93.0  abnormal ...    
376   no      0.0   no  0.0  2.0  11.9    0.0  39.0  124.0  abnormal ...    
377   no      0.0   no  0.0  1.0  10.3    0.0  28.0  234.0  abnormal ...    
378   no  19100.0   no  3.8  2.0  10.0  136.0  30.0  117.0  abnormal ...    
379   no      0.0   no  4.1  0.0  11.3  140.0  35.0  131.0    normal ...    
380   no      0.0   no  4.3  0.0   0.0  135.0   0.0  101.0    normal ...    
381   no   5800.0  yes  4.5  3.0  11.3  133.0  31.0  352.0  abnormal ...    
382   no      0.0   no  4.4  1.0  12.0  138.0  34.0   99.0    normal ...    
383   no      0.0   no  3.8  4.0   0.0  135.0   0.0    0.0    normal ...    
384   no  12300.0   no  0.0  2.0  10.7    0.0  34.0    0.0    normal ...    
385   no      0.0   no  3.6  0.0  12.2  142.0  38.0   80.0         0 ...    
386   no   7500.0  yes  5.4  4.0   9.5  137.0  29.0  239.0  abnormal ...    
387   no  16700.0   no  4.9  4.0   9.9  135.0  30.0   94.0  abnormal ...    
388   no   9200.0  yes  2.7  3.0   9.1  134.0  26.0  110.0    normal ...    
389   no      0.0   no  0.0  0.0   0.0    0.0   0.0  130.0    normal ...    
3

In [30]:
misDF.dropna(inplace=True)

In [32]:
misDF.head()

ane     wbcc  htn  pot   al  hemo    sod   pcv    bgr        pc ...   \
7   yes   9800.0  yes  5.7  4.0   7.3  135.0  20.0  255.0    normal ...    
10   no   7400.0  yes  4.9  3.0  10.9  137.0  34.0  214.0  abnormal ...    
22   no  12000.0  yes  3.8  3.0  11.5  131.0  35.0  490.0    normal ...    
23   no   7500.0  yes  4.6  4.0   7.9  140.0  26.0  163.0  abnormal ...    
26   no  15700.0   no  2.9  3.0   9.6  114.0  31.0  241.0  abnormal ...    

       bp rbcc class       rbc   age   su         mrn    sc     sg  cad  
7   100.0  3.9   ckd    normal  59.0  2.0  3026473899  12.8  1.015  yes  
10   80.0  3.7   ckd    normal  55.0  1.0  7047451479   3.9  1.010   no  
22   90.0  4.5   ckd  abnormal  60.0  5.0  2800591917   2.7  1.010   no  
23  100.0  3.4   ckd  abnormal  64.0  2.0  7827027143   7.2  1.015   no  
26   50.0  3.8   ckd    normal  59.0  0.0  8763895308  12.0  1.010   no  

[5 rows x 26 columns]

In [33]:
misDF.reset_index(inplace=True)
misDF.head()

index  ane     wbcc  htn  pot   al  hemo    sod   pcv    bgr ...      bp  \
0      7  yes   9800.0  yes  5.7  4.0   7.3  135.0  20.0  255.0 ...   100.0   
1     10   no   7400.0  yes  4.9  3.0  10.9  137.0  34.0  214.0 ...    80.0   
2     22   no  12000.0  yes  3.8  3.0  11.5  131.0  35.0  490.0 ...    90.0   
3     23   no   7500.0  yes  4.6  4.0   7.9  140.0  26.0  163.0 ...   100.0   
4     26   no  15700.0   no  2.9  3.0   9.6  114.0  31.0  241.0 ...    50.0   

  rbcc class       rbc   age   su         mrn    sc     sg  cad  
0  3.9   ckd    normal  59.0  2.0  3026473899  12.8  1.015  yes  
1  3.7   ckd    normal  55.0  1.0  7047451479   3.9  1.010   no  
2  4.5   ckd  abnormal  60.0  5.0  2800591917   2.7  1.010   no  
3  3.4   ckd  abnormal  64.0  2.0  7827027143   7.2  1.015   no  
4  3.8   ckd    normal  59.0  0.0  8763895308  12.0  1.010   no  

[5 rows x 27 columns]

#### data cleaning with regex

In [35]:
dirtyMat = [(0,'monday','<efs> sfsdc <sefsdvdv> erfsdvdrer.'),
           (1,'tuesday','sdkjnvkj 234 5t  <fdbdf> dvcvdfv$%^ <df> wefdfvd')]

In [36]:
dirtyDF = pd.DataFrame(dirtyMat)

In [37]:
dirtyDF

0        1                                                 2
0  0   monday                <efs> sfsdc <sefsdvdv> erfsdvdrer.
1  1  tuesday  sdkjnvkj 234 5t  <fdbdf> dvcvdfv$%^ <df> wefdfvd

In [42]:
import re
re.sub('<\S+>','','<efs> sfsdc <sefsdvdv> erfsdvdrer.')

' sfsdc  erfsdvdrer.'

In [43]:
dirtyDF[2] = dirtyDF[2].apply(lambda x : re.sub('<\S+>','',x))

In [44]:
dirtyDF

0        1                                      2
0  0   monday                     sfsdc  erfsdvdrer.
1  1  tuesday  sdkjnvkj 234 5t   dvcvdfv$%^  wefdfvd

https://pythex.org/

#### MISC.

Read about other datastructures in python, sets, dict , tuple etc.  
Read about OOPs concepts in python

more details still doable - https://python.swaroopch.com/
